development:
  adapter: postgresql
  encoding: unicode
  database: canvasmkr_dev
  pool: 5
  username: jcopeman
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: canvasmkr_test
  pool: 5
  username: jcopeman
  password:
